language: python

matrix:
  include:
    - sudo: required
      services:
        - docker
      env:
        - CIBW_BUILD: {cp,pp}3*-*
        - CIBW_SKIP: "*-win32 *-manylinux_i686"
        - PIP=pip
        - PYTHON=python
    - os: osx
      language: generic
      env:
        - PIP=pip
        - PYTHON=python

env:
  global:
    - TWINE_USERNAME=jdrtommey
      # Note: TWINE_PASSWORD is set in Travis settings

script:
  - $PIP install cibuildwheel setuptools_rust
  - export CIBW_BEFORE_BUILD='pip install setuptools-rust && source {project}/ci/install_rust.sh'
  - export CIBW_SKIP=cp34-*\ $CIBW_SKIP
  - export CIBW_ENVIRONMENT='PATH="$HOME/rust/bin:$PATH"'
  - cibuildwheel --output-dir wheelhouse
  - $PIP install twine
  - $PYTHON -m twine upload --repository testpypi wheelhouse/*.whl
    
