language: python

matrix:
  include:
    - sudo: required
      services:
        - docker
      env:
        - CIBW_BUILD='{cp,pp}3*-*'
        - CIBW_SKIP='*-win32 *-manylinux_i686'
        - PIP=pip
        - PYTHON=python
    - os: osx
      language: generic
      env:
        - PIP=pip2
        - PYTHON=python2

env:
  global:
    - TWINE_USERNAME=jdrtommey
    - TWINE_PASSWORD=testfoopassword

script:
  - $PIP install cibuildwheel setuptools_rust
  - export CIBW_BEFORE_BUILD='pip install setuptools-rust && source {project}/ci/install_rust.sh'
  - export CIBW_SKIP=cp27-*\ cp33-*\ cp34-*\ cp35-*\ $CIBW_SKIP
  - export CIBW_ENVIRONMENT='PATH="$HOME/.cargo/bin:$PATH"'
  - cibuildwheel --output-dir wheelhouse
  - $PIP install twine
  - $PYTHON -m twine upload --repository testpypi wheelhouse/*.whl
    
