name: Build

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main 
              
jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-10.15]

    steps:
      - uses: actions/checkout@v2

      - name: Build wheels
        uses: pypa/cibuildwheel@v1.12.0
        env: 
            CIBW_BUILD: '{cp,pp}3*-*'
            CIBW_BEFORE_BUILD: 'pip install setuptools-rust && source {project}/.github/workflows/install_rust.sh'
            CIBW_SKIP: 'cp27-*\ cp33-*\ cp34-*\ cp35-*\ *-win32\ *-manylinux_i686'
            CIBW_ENVIRONMENT: 'PATH="$HOME/.cargo/bin:$PATH"'

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl

  build_sdist:
        name: Build Source distribution
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-python@v2
              name: Install Python
              with: 
                python-version: '3.8'

            - name: Build sdist
              run: python setup.py sdist

            - uses: action/upload-artifact@v2
              with:
                path: dist/*.tar.gz


  upload_pypi:
        needs: [build_wheels,build_sdist]
        runs-on: ubuntu-latest
        if: github.event_name =='release' && github.event.action  == 'published'
        steps:
            - uses: actions/download-artifact@v2
              with:
                  name: artifact
                  path: dist
            - uses: pypa/gh-action-pypi-publish@v1.4.2
              with:
                  user: jdrtommey 
                  password: ${{ secrets.TWINE_PASSWORD }}
                  repository_url: https://test.pypi.org/legacy/
